### ISSUE TITLE
Cuál es el programa GIT Bash

### ISSUE THREAD

**Issue by AracelyHeredia** [AlexB4891/curso_ambiente_R_ciencias#5]
En la línea 142 del documento INSTALACIÓN dice abril el programa "GIT Bash" pero no sé cuál es o dónde está, es el mismo que el terminal? yo creo que sería buena idea poner una imagen de lo que es eso para que sepan donde pegar

**Comment by AlexB4891** [comment]
Katherine, Git Bash es el programa default que se se descarga cuando instalamos el Git con homebrew en tu caso. La consola que se muestra en la guía sería git bash, conversemos el miercoles para cambiar la imagen y hacerla más visual. Gracias
